# test version
name: Airflow Deployment

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'airflow/dags/**'
# GCP 환경설정
env:
  PROJECT_ID: strayanimal
  GCE_INSTANCE: vm-docker-airflow # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-east4-a # TODO: update to instance zone
  USER: kangdiamond

jobs:
  update-dags:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airflow
    steps:
    # 해당 레포지토리로 check-out하는 Action을 불러왔습니다.
    - name: Checkout airflow folder
      uses: actions/checkout@v3
      with: 
        sparse-checkout: 'airflow'
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: '"${{ env.GCE_INSTANCE }}"'
        zone: '"${{ env.GCE_INSTANCE_ZONE }}"'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: 'echo Hello world'