# test version
name: Airflow Deployment
on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'airflow/dags/**'
# GCP 환경설정
env:
  PROJECT_ID: strayanimal
  GCE_INSTANCE: vm-docker-airflow # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-east4-a # TODO: update to instance zone

jobs:
  update-dags:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airflow
    steps:
    # 해당 레포지토리로 check-out하는 Action을 불러왔습니다.
    - uses: actions/checkout@v3
      with: 
        sparse-checkout: 'airflow/**'
      
    - name: 'checkout test'
      run: ls -al
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
