# test version
name: Airflow Deployment
# 메인의 경우 무조건 PR로 들어감 -> PR이 종료되어 merge가 되었을 경우에만 
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'airflow/**'
  push:
    branches:
      - 'develop'
    paths:
      - 'airflow/**'
# GCP 환경설정
env:
  PROJECT_ID: strayanimal
  GCE_INSTANCE: vm-docker-airflow
  GCE_INSTANCE_ZONE: us-east4-a

jobs:
  update-dags:
    # if#: github.event.pull_request.merged
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airflow
    steps:

    - name: Checkout airflow folder
      uses: actions/checkout@v3
      with: 
        sparse-checkout: 'airflow'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    
    - name: 'Set SSH key pair file'
      run: |
        cd ~
        mkdir .ssh
        cd .ssh
        echo "${{ secrets.GCP_PRIVATE_SSH_KEY }}">>google_compute_engine
        echo "${{ secrets.GCP_PUBLIC_SSH_KEY }}">>google_compute_engine.pub
        chmod 400 google_compute_engine

    - name: 'Copy Github airflow folder gcloud Commands SCP'    
      run: gcloud compute scp 
        --zone=${{ env.GCE_INSTANCE_ZONE }}
        --project=${{ env.PROJECT_ID }} --recurse
        /home/runner/work/project2-team1/project2-team1/airflow runner@${{ env.GCE_INSTANCE }}:~
