name: Firebase Webapp Deploy Hosting
  
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "strayanimal-app/**"

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./strayanimal-app
    
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'strayanimal-app'
      - name: Set up node (16)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: 'Build Application'
        run: |
          cd strayanimal && npm ci
          cd ..
          npm ci && npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./strayanimal-app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRAYANIMAL }}"
          projectId: strayanimal
          channelId: live