name: Firebase Webapp Deploy Hosting
  
on:
  push:
  #pull_request:
  #  types:
  #    - closed
  #  branches:
  #    - main
  #    - develop
  #  paths:
  #    - "strayanimal-app/**"

jobs:
  build:
    #if#: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: firebase
    defaults:
      run:
        working-directory: ./strayanimal-app
    
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: 'strayanimal-app'
      - name: Set up node (16)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create env file
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_ID: ${{ secrets.REACT_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
        run: |
          cd strayanimal
          touch .env
          echo REACT_APP_API_KEY="$REACT_APP_API_KEY" >> .env
          echo REACT_APP_AUTH_DOMAIN="$REACT_APP_AUTH_DOMAIN" >> .env
          echo REACT_APP_PROJECT_ID="$REACT_APP_PROJECT_ID" >> .env
          echo REACT_APP_STORAGE_BUCKET="$REACT_APP_STORAGE_BUCKET" >> .env
          echo REACT_APP_MESSAGING_SENDER_ID="$REACT_APP_MESSAGING_SENDER_ID" >> .env
          echo REACT_APP_ID="$REACT_APP_ID" >> .env
          echo REACT_APP_MEASUREMENT_ID="$REACT_APP_MEASUREMENT_ID" >> .env

      - name: 'Build Application'
        run: |
          cd strayanimal && npm ci
          cd ..
          npm ci && npm run build

      - run: npm test

      - run: |
          ls -al
          pwd

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: /
  deploy:
    #if#: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./strayanimal-app
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: /
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STRAYANIMAL }}"
          projectId: strayanimal
          channelId: live
